Productos = [
    "producto: Yogur natural, marca: Soprole, precio: $1.200",
    "producto: Leche entera 1L, marca: Colún, precio: $1.050",
    "producto: Pan de molde, marca: Todo Día, precio: $2.500",
    "producto: Huevos 12u, marca: Avícola Chile, precio: $3.200",
    "producto: Arroz largo, marca: Nuestra Cocina, precio: $1.800",
    "producto: Fideos tallarines, marca: Líder, precio: $1.100",
    "producto: Aceite vegetal 1L, marca: Cocinero, precio: $2.900",
    "producto: Azúcar rubia 1kg, marca: Nuestra Cocina, precio: $1.600",
    "producto: Harina 1kg, marca: Todo Día, precio: $1.400",
    "producto: Mantequilla 250g, marca: Soprole, precio: $3.500",
    "producto: Queso fresco 500g, marca: Colún, precio: $4.200",
    "producto: Jamón de pollo 200g, marca: Fuentetaja, precio: $3.800",
    "producto: Mortadela 200g, marca: Fuentetaja, precio: $2.900",
    "producto: Palta hass 1u, marca: N/A, precio: $1.500",
    "producto: Tomate por kilo, marca: N/A, precio: $1.800",
    "producto: Cebolla por kilo, marca: N/A, precio: $1.200",
    "producto: Papas por kilo, marca: N/A, precio: $1.000",
    "producto: Manzanas gala kg, marca: N/A, precio: $2.200",
    "producto: Banano por kilo, marca: N/A, precio: $1.400",
    "producto: Naranja por kilo, marca: N/A, precio: $1.600",
    "producto: Pavo magro 200g, marca: Fuentetaja, precio: $4.100",
    "producto: Pollo entero kg, marca: Ariztía, precio: $3.900",
    "producto: Carne molida kg, marca: N/A, precio: $6.500",
    "producto: Salchichas frescas, marca: Wieners, precio: $3.200",
    "producto: Atún en lata 170g, marca: Austral, precio: $1.700",
    "producto: Mayonesa 390g, marca: Hellmann's, precio: $2.800",
    "producto: Kétchup 390g, marca: Todo Día, precio: $1.500",
    "producto: Mostaza 200g, marca: Nuestra Cocina, precio: $1.200",
    "producto: Galletas maría 200g, marca: Fontana, precio: $1.900",
    "producto: Biscotes 250g, marca: Todo Día, precio: $2.100",
    "producto: Cereal corn flakes, marca: Kellogg's, precio: $4.500",
    "producto: Avena 500g, marca: Quaker, precio: $2.700",
    "producto: Mermelada frutilla 390g, marca: Conservas Chile, precio: $2.400",
    "producto: Miel 500g, marca: Nuestra Cocina, precio: $4.000",
    "producto: Chocolate con leche 100g, marca: Lindt, precio: $2.200",
    "producto: Galletas oreo 150g, marca: Oreo, precio: $2.600",
    "producto: Papel tissue 12u, marca: Elite, precio: $5.900",
    "producto: Jabón líquido 500ml, marca: Asepxia, precio: $2.500",
    "producto: Detergente 1kg, marca: Ala, precio: $4.800",
    "producto: Suavizante 1L, marca: Downy, precio: $5.200",
    "producto: Cerveza Cristal 6u, marca: CCU, precio: $6.500",
    "producto: Vino tinto 750ml, marca: Santa Carolina, precio: $5.900",
    "producto: Agua mineral 6u 1.5L, marca: Cachantun, precio: $3.800",
    "producto: Jugo de naranja 1L, marca: Jumex, precio: $2.100",
    "producto: Refresco cola 2L, marca: Coca Cola, precio: $2.400",
    "producto: Yogur griego, marca: Soprole, precio: $1.800",
    "producto: Requesón 200g, marca: Colún, precio: $2.900",
    "producto: Mantejar 250g, marca: Colún, precio: $3.000",
    "producto: Pasta dental 100ml, marca: Colgate, precio: $2.200",
    "producto: Desodorante roll on, marca: Rexona, precio: $2.800",
    "producto: Shampoo 400ml, marca: Pantene, precio: $4.500",
]